

10:35:23 AM: DEBUG [personaDaoControl.py:33] [31miD: 22[39m


10:35:23 AM: INFO [personaDaoControl.py:35] [34mnuevo id = 23[39m


10:35:23 AM: DEBUG [personaDaoControl.py:33] [31miD: 23[39m


10:35:23 AM: INFO [personaDaoControl.py:35] [34mnuevo id = 24[39m


10:35:23 AM: DEBUG [personaDaoControl.py:33] [31miD: 24[39m


10:35:23 AM: INFO [personaDaoControl.py:35] [34mnuevo id = 25[39m


10:35:23 AM: DEBUG [personaDaoControl.py:33] [31miD: 25[39m


10:35:23 AM: INFO [personaDaoControl.py:35] [34mnuevo id = 26[39m


10:35:23 AM: DEBUG [personaDaoControl.py:33] [31miD: 26[39m


10:35:23 AM: INFO [personaDaoControl.py:35] [34mnuevo id = 27[39m


10:04:51 PM: DEBUG [personaDaoControl.py:32] [31miD: 4[39m


10:04:51 PM: INFO [personaDaoControl.py:34] [34mnuevo id = 5[39m


10:13:59 PM: DEBUG [personaDaoControl.py:37] [32mError en save es: 'str' object has no attribute '__lenj__'[39m


10:21:14 PM: DEBUG [personaDaoControl.py:37] [32mError en save es: unsupported operand type(s) for +: 'int' and 'str'[39m


10:27:54 PM: DEBUG [personaDaoControl.py:37] [32mError en save es: string index out of range[39m


10:30:58 PM: DEBUG [personaDaoControl.py:37] [32mError en save es: string indices must be integers, not 'tuple'[39m


12:05:04 AM: DEBUG [personaDaoControl.py:37] [32mError en save es: commit[39m
